Repository playcanvas/model-viewer, pull requests merged in 2020-07, with the labels that each got.

#2 Add serve script, PR template, license
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  package-lock.json
  package.json
Labels: enhancement

#6 [FIX] Update engine files
  playcanvas-extras.js
  playcanvas.js
Labels: bug

#5 [FIX] Force render on window resize
  src/viewer.js
Labels: bug

#9 Add support for meshopt, remove html scripts, remove use_local_engine
  README.md
  index.html
  lib/meshopt/meshopt_decoder.js
  playcanvas-extras.js
  playcanvas.js
  src/controls.js
  src/viewer.js
Labels: enhancement

#16 Remove engine sources and update callbacks for engine change
  playcanvas-extras.js
  playcanvas.js
  src/viewer.js
Labels: enhancement

#17 Use new anim component
  src/controls.js
  src/viewer.js
Labels: enhancement

#18 Morphs update
  src/controls.js
  src/viewer.js
  webpack.config.js
Labels: enhancement

#19 Fix playcanvas logo for server builds
  src/index.ejs
  webpack.config.js
Labels: bug

#20 Update NPM dependencies
  package-lock.json
  package.json
Labels: enhancement

#22 Add load param
  src/viewer.js
Labels: enhancement

#27 Add meta tags for Google listing
  src/index.ejs
Labels: enhancement

#31 Remove shiny ball, anim fix
  src/viewer.js
Labels: bug

#32 viewer updates
  src/controls.js
  src/cta.js
  src/index.ejs
  src/index.js
  src/lib/pcui.js
  src/style.css
  src/viewer.js
  webpack.config.js
Labels: bug, enhancement
