Repository playcanvas/model-viewer, pull requests merged in 2020-08, with the labels that each got.

#40 Fix HDR issue
  .gitignore
  src/lib/hdr-texture.js
Labels: bug

#42 Support local builds of the playcanvas engine
  package.json
  src/controls.js
  src/helpers.js
  src/index.js
  src/viewer.js
  webpack.config.js
Labels: enhancement

#43 Add npm local script for watching and serving
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#49 Readme update for local engine builds
  README.md
Labels: documentation

#48 Typescript
  lib/download-texture.js
  lib/hdr-texture.js
  lib/meshopt_decoder.js
  lib/pcui.js
  lib/wasm-loader.js
  package-lock.json
  package.json
  src/controls.ts
  src/cta.ts
  src/debug.js
  src/debug.ts
  src/graph.ts
  src/helpers.js
  src/helpers.ts
  src/index.ts
  src/viewer.ts
  tsconfig.json
  webpack.config.js
Labels: enhancement

#50 Controls update
  package-lock.json
  package.json
  src/controls.ts
  src/graph.ts
  src/index.ts
  src/viewer.ts
  static/asset_manifest.json
  static/skybox/Helipad_equi_small.png
Labels: enhancement

#51 Add anim loops
  src/controls.ts
  src/viewer.ts
Labels: bug, enhancement

#52 Server build typescript error fix
  src/controls.ts
  src/cta.ts
  src/index.ts
  src/viewer.ts
Labels: bug

#54 Fix startup console error
  src/viewer.ts
Labels: bug
